name: tea_brew_networking
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  json_annotation: ^4.5.0
  graphql: 5.1.1

dev_dependencies:
  lints: ^2.0.0
  graphql_codegen: ^0.8.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0