name: tea_brew_networking
description: TeaBrew Networking Module
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  graphql: 5.1.1

dev_dependencies:
  graphql_codegen: ^0.8.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0